### ISSUE TITLE
Any plans on 0.4 compatibility?

### ISSUE THREAD

**Issue by nilshg** [ajt60gaibb/FastGaussQuadrature.jl#14]
I'm using the package on 0.4 and got a bunch of deprecation warnings. A lot of them are quite easily fixed (such as replacing `[]` concatenation with `collect()`, e.g. [here](https://github.com/ajt60gaibb/FastGaussQuadrature.jl/blob/master/src/gausshermite.jl#L186)).

What are the plans for 0.4 compatibility? Are PR's on this welcome?

**Comment by ajt60gaibb** [comment]
Of course PR's are very welcome.

**Comment by nilshg** [comment]
Okay, I've made one that should get rid of warnings for `gausshermite()` that occured when using in between 20 and 200 nodes. One function at a time, I guess :)
