### ISSUE TITLE
Citation for published work?

### ISSUE THREAD

**Issue by nilshg** [ajt60gaibb/FastGaussQuadrature.jl#16]
As I've used FGQ in my thesis, I was wondering whether there's a suggested way of citing the package?

**Comment by ajt60gaibb** [comment]
A. Townsend, http://www.github.com/ajt60gaibb/FastGaussQuadrature.jl/, GitHub repository, 2015. 

Depending on what aspect of the package you are using, you may also wish to reference one of the papers from here: https://github.com/ajt60gaibb/FastGaussQuadrature.jl

When you are ready, please send me a reference for your thesis and I would like to add a link to it. Thanks.

**Comment by nilshg** [comment]
Cool, thanks. Citation is [here](https://github.com/nilshg/Thesis/blob/master/thesis_bibliography.bib#L3340) (thesis itself is still under heavy development though...)
