### ISSUE TITLE
Typos?

### ISSUE THREAD

**Issue by MikaelSlevinsky** [ajt60gaibb/FastGaussQuadrature.jl#20]
chebfun/chebfun#1621

Potentially related issue: chebfun/chebfun#1622

**Comment by ajt60gaibb** [comment]
The typos do not exist in `gaussjacobi` because the algorithm does not rely on the boundary asymptotic expansion for Jacobi polynomials.

**Comment by MikaelSlevinsky** [comment]
Probably Reinsch's modified recurrence relation should be used near the boundary, then?

**Comment by ajt60gaibb** [comment]
Good point.
