### ISSUE TITLE
Tag a new release?

### ISSUE THREAD

**Issue by panlanfeng** [ajt60gaibb/FastGaussQuadrature.jl#21]
How about tag a new release? The deprecation warning in v0.01 is annoying. 
If some package is depending on this, it is inconvenient to `Pkg.checkout` everytime when install in a new computer.

**Comment by dlfivefifty** [comment]
I’ve just tagged a new release, once the tests pass I’ll push it to METADATA.

**Comment by panlanfeng** [comment]
Thanks!
