### ISSUE TITLE
incorrect call to flipdim in HermiteInitialGuesses?

### ISSUE THREAD

**Issue by stevengj** [ajt60gaibb/FastGaussQuadrature.jl#36]
The function HermiteInitialGuesses [calls `flipdim(x_init, 2)`](https://github.com/ajt60gaibb/FastGaussQuadrature.jl/blob/ea4a091333c861e0e679482a1331b8428e2cc493/src/gausshermite.jl#L212), but the `x_init` array appears to be a 1d array.  Currently, this means that `flipdim` is a no-op, but it may soon change to an error (JuliaLang/julia#17752).

Is this a bug?

**Comment by stevengj** [comment]
I should also point out that calling `HermiteInitialGuesses` with an argument smaller than `20` throws a `BoundsError`; not sure if this is intentional.

**Comment by ajt60gaibb** [comment]
It was not actually a no-op.  The code was essentially doing this:
```
x = collect(1:10)'
flipdim(x,2)
[10 9 8 7 6 5 4 3 2 1]
```
I have changed things to use `flipdim(x,1)`.

**Comment by stevengj** [comment]
Oh, okay, I didn't notice the `'` that made it a row vector.  `flipdim(x,2)` is fine (in both 0.4 and 0.5) for a 2d array, of course.
