### ISSUE TITLE
Clenshaw-Curtis?

### ISSUE THREAD

**Issue by AshtonSBradley** [ajt60gaibb/FastGaussQuadrature.jl#49]
thanks for your great code... any scope for adding Clenshaw-Curtis quadrature?

**Comment by MikaelSlevinsky** [comment]
Clenshaw-Curtis quadrature is implemented in [FastTransforms.jl](https://github.com/MikaelSlevinsky/FastTransforms.jl) for a Jacobi weight.

**Comment by AshtonSBradley** [comment]
awesome, thanks for the pointer
