### ISSUE TITLE
Weights don't sum to 1

### ISSUE THREAD

**Issue by tbeason** [ajt60gaibb/FastGaussQuadrature.jl#54]
I'm using Gauss-Laguerre with a small number of nodes (between 3 and 15). If I only supply the number of nodes that I want, the weights sum to 1 as I would expect. If I supply a second argument, the weights stop summing to 1. Sometimes they are lower, sometimes higher. I am not super familiar with gauss-laguerre (I usually use gauss-hermite), but I am used to thinking of these as normalized weights that should sum to 1. Is that correct? If so, what is going on here?

For reference, I am trying to use this to compute the expectation of a random variable that has an exponential distribution with parameter t>0 (so that E[x]=1/t). 

```julia
n,w = gausslaguerre(7,0.075)
sum(w)     # = 0.961918
```

**Comment by tbeason** [comment]
Ah I think I see my problem. The second parameter is _not_ for the parameter of the distribution, but for some general weight function. Correct?

So, I should be using 
```julia
n,w=gausslaguerre(7)
n=0.075*n
```
to get the proper nodes and weights.

**Comment by dlfivefifty** [comment]
`gausslaguerre(n,α)` is for integrating with respect to the weight `x^α*exp(-x)`, so that `sum(w)` equals $\int_0^\infty x^\alpha*exp(-x) dx$, which is precisely `gamma(α+1)`:
```julia 
julia> gamma(0.75+1)
0.9190625268488832
```
