### ISSUE TITLE
Remove type annotations on N

### ISSUE THREAD

**Issue by pkofod** [ajt60gaibb/FastGaussQuadrature.jl#56]
There should be no reason to restrict `N` to either `Int` (which is `Int32` on 32bit systems and `Int64` on 64bit systems) or `Int64`. If you try to use Gauss-Laguerre on a 32bit system and type in `16` as the number of nodes, it will fail because it's restricted to be `Int64`. In Gauss-Hermite an `Int64` version of `16` will fail, as that is type-annotated as `Int`. Did you mean `Integer` in these cases?

```julia
f(x::Int) = x
```
will only work for `Int32` on 32bit systems and `Int64` on 64bit systems, while
```julia
f(x::Integer) = x
```
will work for both on both systems. 

ref https://github.com/pkofod/DistQuads.jl/pull/4

**Comment by dlfivefifty** [comment]
Just fixed this in master

**Comment by pkofod** [comment]
Perfect
