### ISSUE TITLE
Pkg.publish() FastGuassQuadrature.jl so others can use in REQUIRE

### ISSUE THREAD

**Issue by dlfivefifty** [ajt60gaibb/FastGaussQuadrature.jl#9]
I'd like to add it to a REQUIRE file but can't since it hasn't been published to METADATA yet.

**Comment by KristofferC** [comment]
Same here. It is a nice package.

**Comment by dlfivefifty** [comment]
I think I've been added to the repository so I can probably do this now

**Comment by dlfivefifty** [comment]
Unless Alex objects
